# -*- coding: utf-8 -*-
"""(Sentiment Analysis)app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NcAzAIqKrs55Dplhbs1X8DnJe8MVZXE9
"""

import pandas as pd
import joblib
import streamlit as st
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Example training data
X = ["I love this movie", "This movie is bad"]
y = ["positive", "negative"]

# Vectorize text
vectorizer = TfidfVectorizer()
X_vect = vectorizer.fit_transform(X)

#Train model
model = LogisticRegression()
model.fit(X_vect, y)

import joblib

joblib.dump(model, "model.pkl")          # Saves the trained model
joblib.dump(vectorizer, "vectorizer.pkl")  # Saves the vectorizer

model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

st.title("NLP Sentiment Analysis")

text = st.text_area("Enter your Review")

if st.button("Predict"):
    data = vectorizer.transform([text])
    result = model.predict(data)[0]
    st.write("Prediction:", result)

